/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelId = IDL.Nat;
export const ProfileId = IDL.Principal;
export const Channel = IDL.Record({
  'creator' : ProfileId,
  'channelId' : ChannelId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Status = IDL.Variant({
  'away' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'status' : Status,
  'username' : IDL.Text,
  'profileId' : IDL.Principal,
  'avatarUrl' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ChannelMessage = IDL.Record({
  'content' : IDL.Text,
  'channelId' : ChannelId,
  'messageId' : MessageId,
  'sender' : ProfileId,
  'timestamp' : Timestamp,
});
export const ConversationId = IDL.Nat;
export const DirectMessage = IDL.Record({
  'content' : IDL.Text,
  'messageId' : MessageId,
  'recipient' : ProfileId,
  'sender' : ProfileId,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelId], []),
  'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getAllOnlineUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelMembers' : IDL.Func([ChannelId], [IDL.Vec(ProfileId)], ['query']),
  'getChannelMessages' : IDL.Func(
      [ChannelId, IDL.Nat],
      [IDL.Vec(ChannelMessage)],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [ConversationId, IDL.Nat],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getPinnedMessages' : IDL.Func(
      [ChannelId],
      [IDL.Vec(ChannelMessage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinChannel' : IDL.Func([ChannelId], [], []),
  'pinMessage' : IDL.Func([ChannelId, MessageId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendDirectMessage' : IDL.Func([ProfileId, IDL.Text], [], []),
  'sendMessage' : IDL.Func([ChannelId, IDL.Text], [], []),
  'updateStatus' : IDL.Func([IDL.Principal, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelId = IDL.Nat;
  const ProfileId = IDL.Principal;
  const Channel = IDL.Record({
    'creator' : ProfileId,
    'channelId' : ChannelId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Status = IDL.Variant({
    'away' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'status' : Status,
    'username' : IDL.Text,
    'profileId' : IDL.Principal,
    'avatarUrl' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ChannelMessage = IDL.Record({
    'content' : IDL.Text,
    'channelId' : ChannelId,
    'messageId' : MessageId,
    'sender' : ProfileId,
    'timestamp' : Timestamp,
  });
  const ConversationId = IDL.Nat;
  const DirectMessage = IDL.Record({
    'content' : IDL.Text,
    'messageId' : MessageId,
    'recipient' : ProfileId,
    'sender' : ProfileId,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelId], []),
    'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getAllOnlineUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelMembers' : IDL.Func(
        [ChannelId],
        [IDL.Vec(ProfileId)],
        ['query'],
      ),
    'getChannelMessages' : IDL.Func(
        [ChannelId, IDL.Nat],
        [IDL.Vec(ChannelMessage)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [ConversationId, IDL.Nat],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getPinnedMessages' : IDL.Func(
        [ChannelId],
        [IDL.Vec(ChannelMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinChannel' : IDL.Func([ChannelId], [], []),
    'pinMessage' : IDL.Func([ChannelId, MessageId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendDirectMessage' : IDL.Func([ProfileId, IDL.Text], [], []),
    'sendMessage' : IDL.Func([ChannelId, IDL.Text], [], []),
    'updateStatus' : IDL.Func([IDL.Principal, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };