/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'creator' : ProfileId,
  'channelId' : ChannelId,
  'name' : string,
  'description' : string,
}
export type ChannelId = bigint;
export interface ChannelMessage {
  'content' : string,
  'channelId' : ChannelId,
  'messageId' : MessageId,
  'sender' : ProfileId,
  'timestamp' : Timestamp,
}
export type ConversationId = bigint;
export interface DirectMessage {
  'content' : string,
  'messageId' : MessageId,
  'recipient' : ProfileId,
  'sender' : ProfileId,
  'timestamp' : Timestamp,
}
export type MessageId = bigint;
export type ProfileId = Principal;
export type Status = { 'away' : null } |
  { 'offline' : null } |
  { 'online' : null };
export type Timestamp = bigint;
export interface UserProfile {
  'bio' : string,
  'status' : Status,
  'username' : string,
  'profileId' : Principal,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<[string, string], ChannelId>,
  'getAllChannels' : ActorMethod<[], Array<Channel>>,
  'getAllOnlineUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelMembers' : ActorMethod<[ChannelId], Array<ProfileId>>,
  'getChannelMessages' : ActorMethod<
    [ChannelId, bigint],
    Array<ChannelMessage>
  >,
  'getDirectMessages' : ActorMethod<
    [ConversationId, bigint],
    Array<DirectMessage>
  >,
  'getPinnedMessages' : ActorMethod<[ChannelId], Array<ChannelMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinChannel' : ActorMethod<[ChannelId], undefined>,
  'pinMessage' : ActorMethod<[ChannelId, MessageId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDirectMessage' : ActorMethod<[ProfileId, string], undefined>,
  'sendMessage' : ActorMethod<[ChannelId, string], undefined>,
  'updateStatus' : ActorMethod<[Principal, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];